// src/styles/theme.js
export const theme = {
  colors: {
    background: "#2e2e2e",
    cardBackground: "#4a4a4a",
    shadowColor: "#000",
    textPrimary: "#f0f0f0",
    textSecondary: "#b0b0b0",
    accent: "#FF6B6B",
    headerBackground: "#1e352f",
    headerText: "#d3d3d3",
    badgeBackground: "#1e3d32",
    badgeShadow: "#0f201a",
    switchTrackOff: "#555555",
    switchTrackOn: "#3a6b4f",
    switchThumb: "#f0f0f0",
    greenButtonBackground: "#3a6b4f",
    greenButtonText: "#f0f0f0",
    grayButtonBackground: "#6c6c6c",
    grayButtonText: "#f0f0f0",
    sectionBackground: "#3c3c3c",
    inputBackground: "#505050",
    inputBorder: "#666666",
    pickerBackground: "#4a4a4a",
    pickerText: "#f0f0f0",
  },
  spacing: {
    xsmall: 4,
    small: 8,
    medium: 16,
    large: 24,
  },
  borderRadius: {
    small: 6,
    medium: 8,
    large: 12,
  },
  typography: {
    headerFontSize: 20,
    headerFontWeight: "700",
    bodyFontSize: 16,
    labelFontSize: 14,
    inputFontSize: 14,
  },
};
